package com.ndrmf.util.enums;

public enum ProcessType {
	ELIGIBILITY, QUALIFICATION, ACCREDITATION_QUESTIONNAIRE, PROJECT_PROPOSAL,
	PRELIMINARY_APPRAISAL, EXTENDED_APPRAISAL, GIA, GIA_CHECKLIST,
	SUB_PROJECT_DOCUMENT, DISBURSEMENT, QPR, QPR_TO_DONOR
}